language: node_js
node_js:
- 10
branches:
  only:
  - master
install:
  - yarn --ignore-engines
  - yarn add up-env --ignore-engines
before_script:
  - node_modules/.bin/up-env load --region us-east-1
script:
  - yarn add travis-up
before_deploy:
  - ./bin/up version
deploy:
  provider: script
  script: ./bin/up deploy production
  skip_cleanup: true

env:
  global:
    AWS_REGION: us-west-2