language: node_js
node_js:
- 9
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_21f2578023fe_key -iv $encrypted_21f2578023fe_iv -in env.js.enc -out edge/env.js -d
install:
- yarn --ignore-engines
script:
- yarn run build
after_script:
- yarn run deploy