language: node_js
node_js:
- 9
branches:
  only:
  - master
before_install:
- curl -sf https://up.apex.sh/install | sh
- up version
- npm i -g up-env
install:
- yarn --ignore-engines
- mkdir up
- cp up.json up/
script:
- yarn run build:up
after_script: